diario_adm_default:
    path:     /
    defaults: { _controller: DiarioAdmBundle:Default:index }

DiarioAdmBundle_diario:
    resource: "@DiarioAdmBundle/Resources/config/routing/diario.yml"
    prefix:   /diario
