diario_professor_default:
    path:     /
    defaults: { _controller: DiarioProfessorBundle:Default:index }

DiarioProfessorBundle_turma:
    resource: "@DiarioProfessorBundle/Resources/config/routing/turma.yml"
    prefix:   /turma