diario_professor_default:
    path:     /
    defaults: { _controller: DiarioProfessorBundle:Default:index }

DiarioProfessorBundle_professor:
    resource: "@DiarioProfessorBundle/Resources/config/routing/professor.yml"
    prefix:   /professor
